# this bot will update the dependencies automatically so we don't have to
version: 2
updates:
  # backend: looks in AetherXmlBridge/aetherxmlbridge/pom.xml
  - package-ecosystem: "maven"
    directory: "/aetherxmlbridge"
    schedule:
      interval: "daily"
    groups:
      maven-dependencies:
        patterns:
          - "*"

  # frontend: looks in AetherXmlBridge/frontend/package.json
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # docker: keeps Java/Base images updated
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      docker-dependencies:
        patterns:
          - "*"